config/routes.rb
Rails.application.routes.draw do

  get "keycloak/reset_configuration"
  get "keycloak/impersonate"
  get "keycloak/impersonate_logout"
  get "keycloak/:keycloak_user_id/impersonate" => "keycloak#impersonate_user", as: :impersonate_user
  get "keycloak/change_locale"

  devise_scope :user do
    get '/after_logout' => "users/omniauth_callbacks#logout", as: :post_logout
    get '/after_register' => "users/omniauth_callbacks#after_register"
  end


  devise_for :users, controllers: {
    # registrations: 'users/registrations',
    # sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#welcome"
  get 'home/signed_welcome'
  match 'home/test', via: [:get, :post], as: :test_page
  #get 'home/after_login'

  match 'models/grid_search' => 'entities#grid_search', via: [:get, :post], as: 'models_grid_search'
  post 'vue_grids/save_preferences' => 'entities#save_preferences'

end

app/views/shared/_flash_messages.html.erb
<div class="container-fluid mt-2" id="flash-notifications">
  <% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible">
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      <%= raw message %>
    </div>
  <% end %>
</div>

app/views/shared/_login_redirect.html.erb
<%if @must_login %>
<script>
    onReadyFunction(function(){
        let signInButton=document.querySelector(".sign-in");
        if(signInButton){
            signInButton.click()
        }
    })
</script>
<%end %>

app/views/shared/_navigation_bar.html.erb
<style>

    <% if ServerTools.is_development? %>
    #navigation_bar{
        background-color: sandybrown !important;
    }
    <%else %>
    #navigation_bar{
        background-color: #343a40 !important;
    }
    <% end %>

    .impersonate{
        background-color: red;
    }
</style>
<nav class="navbar navbar-expand-lg bg-body-tertiary" bs id="navigation_bar">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%=root_path %>">
      <%=image_tag 'ptm.png' %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Menu1
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/home/signed_welcome">Signed welcome</a></li>
            <li><%=link_to t('navigation.clients'),  clients_path, class: 'dropdown-item'%></li>
          </ul>
        </li>
        <%end %>
      </ul>

      <%if current_user %>
      <ul class="navbar-nav">
        <li class="nav-item <%= 'impersonate' if Current.true_user %>">
          <div class="dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%=current_user.full_name %>
            </a>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><%=link_to t('navigation.my_account'),  keycloak_account_path, class: 'dropdown-item'%></li>
              <%if Current.true_user %>
                <li><%=link_to t('navigation.impersonate_logout'),  keycloak_impersonate_logout_path, class: 'dropdown-item'%></li>
              <%else %>
                <li><%=link_to t('navigation.logout'),  keycloak_logout_path, class: 'dropdown-item'%></li>
              <%end %>
            </ul>
          </div>
        </li>
        <li class="nav-item">
          <div class="dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fa-solid fa-earth-americas"></i>
            </a>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><%=link_to t('navigation.locales.en'), keycloak_change_locale_path(locale: 'en') , class: current_user.locale=='en' ? 'dropdown-item active': 'dropdown-item'%></li>
              <li><%=link_to t('navigation.locales.fr'),  keycloak_change_locale_path(locale: 'fr'), class: current_user.locale=='fr' ? 'dropdown-item active': 'dropdown-item'%></li>
            </ul>
          </div>
        </li>
        <%if can?(:manage, :all) || (Current.true_user &&  Ability.new(Current.true_user).can?(:manage, :all)) %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fa-solid fa-gear"></i>
            </a>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><%=link_to t('navigation.reload_keycloak_configuration'),  keycloak_reset_configuration_path, class: 'dropdown-item'%></li>
              <li><%=link_to t('navigation.keycloak_admin_console'),  keycloak_admin_console_path, class: 'dropdown-item'%></li>
              <li><%=link_to t('navigation.impersonate'),  keycloak_impersonate_path, class: 'dropdown-item'%></li>
            </ul>
          </li>
        <%end %>
      </ul>
      <%else %>
        <%if Keycloak::Client.get_realm_representation.is_loaded %>
          <%= button_to t('navigation.sign_in'), keycloak_sign_in_path, data: { turbo: false }, class: 'btn btn-primary ms-1 sign-in'%>
          <%if Keycloak::Client.get_realm_representation.is_registration_enabled %>
            <%=link_to t('navigation.register'), keycloak_registration_path, class: 'btn btn-primary ms-1', style: 'appearance: button;'%>
          <%end %>
        <%end %>
      <%end %>
    </div>
  </div>
</nav>

app/views/shared/_on_ready_function_script.html.erb
<script type="text/javascript">
    function onReadyFunction(callback){
        if (
            document.readyState === "complete" ||
            (document.readyState !== "loading" && !document.documentElement.doScroll)
        ) {
            callback();
        } else {
            document.addEventListener("DOMContentLoaded", callback);
        }
    }
    function resizeIframe(obj) {
        obj.style.height = $(obj.contentWindow.document.documentElement).height() + 'px';
    }
</script>

app/views/shared/_set_js_vars.html.erb
<script type="text/javascript">
    var BASE_URL = '<%= root_url.split('?')[0] %>';
    var BASE_PARAMETERS='?<%= root_url.split('?')[1] if root_url.split('?').count>1 %>';
    var CURRENT_PARAMETERS='?<%=request.parameters.map{|k, v| "#{k}=#{v}"}.join('&')%>';
    var LOCALE='locale=<%=I18n.locale%>';
    var current_locale="<%= I18n.default_locale %>";
    var user_full_name='achristen' //'<%#=current_full_name%>';
    var rubyI18nDefaultLocale= "<%= I18n.default_locale %>";
    var rubyI18nLocale="<%= I18n.locale %>";
    var is_user_superadmin=true //<%#=can?(:manage, :all)%>;
    <%if false && current_user%>
    var user_permissions=<%=current_user.ability.permissions[:can].to_json.html_safe%>
    <%end %>
</script>