config/routes.rb
Rails.application.routes.draw do

  get "keycloak/reset_configuration"
  get "keycloak/impersonate"
  get "keycloak/impersonate_logout"
  get "keycloak/:keycloak_user_id/impersonate" => "keycloak#impersonate_user", as: :impersonate_user
  get "keycloak/change_locale"

  devise_scope :user do
    get '/after_logout' => "users/omniauth_callbacks#logout", as: :post_logout
    get '/after_register' => "users/omniauth_callbacks#after_register"
  end


  devise_for :users, controllers: {
    # registrations: 'users/registrations',
    # sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#welcome"
  get 'home/signed_welcome'
  match 'home/test', via: [:get, :post], as: :test_page
  #get 'home/after_login'

  match 'models/grid_search' => 'entities#grid_search', via: [:get, :post], as: 'models_grid_search'
  post 'vue_grids/save_preferences' => 'entities#save_preferences'

end

app/models/client.rb
class Client < GroupScoped
  include Entity::Queryable

  def method_test
    "#{group_name} for #{name}"
  end

  class Grids
    class IndexGrid

      NAME= :index

      def authorize_request
        true
      end

      def base_query
        query = "SELECT clients.*,
            clients.name as made_up_data,
            groups.name as group_name,
            groups.hierarchy as group_hierarchy
          FROM clients
          INNER JOIN groups ON groups.id = clients.group_id
          WHERE clients.name LIKE :user_name
        "
        binds ={
          user_name: "%#{Client.sanitize_sql_like('')}%"
        }
        Client.sanitize_sql([query, **binds])
      end

      def serialize(query)
        query.as_json(
          {
            methods: :method_test
          }
        )
      end

    end
  end


  TEST_CONSTANTS = 'a'

  # add_grid_query :index, Queries::IndexQuery
  define_all_grid_from Grids

end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong>Id:</strong>
    <%= client.id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= client.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= client.address %>
  </p>

</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :id, style: "display: block" %>
    <%= form.number_field :id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this client", @client %> |
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/index.html.erb
<% content_for :head_packs do %>
  <%=vite_javascript_tag 'application'%>
  <%=vite_typescript_tag 'entrypoints/grids/grids'%>
<% end %>

<p style="color: green"><%= notice %></p>

<h1>Clients</h1>

<%=grid(
     layout_manager(
       grid_state(
         id:"clients_index",
         klass: Client,
         proxy: remote_proxy(Client),
         columns: [
           string_column_definition(Client, 'name', 350, sort_direction: VueGrid::SharedHelper::SORT_DIRECTION_ASC),
           string_column_definition(Client, 'address', 450),
         ],

       ),
     )
   ) %>

<%= link_to "New client", new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to "Edit this client", edit_client_path(@client) %> |
  <%= link_to "Back to clients", clients_path %>

  <%= button_to "Destroy this client", @client, method: :delete %>
</div>